name 'dylanratcliffe-winoptionalfeature'
version '0.0.6'
dependency 'joshcooper/powershell', '>=0.0.5'
summary "Installs and Removes Windows Features"
description "This puppet module creates a new defined type 'winoptionalfeature'. This can be called within any
class to install/remove windows features based on their ID string ex: 'Web-Server' or a 
comma seperated list of feature IDs ex: 'Telnet-Client,Telnet-Server' 

The functionality is simply a wrapper to the powershell cmdlets 'Enable-WindowsOptionalFeature' and 'Disable-WindowsOptionalFeature'.
All cmdlet parameters are supported by this module.

Inspired from puppet module: https://forge.puppetlabs.com/admin36/winfeature"
source "https://github.com/dylanratcliffe1/winoptionalfeature"
project_page ""
author "Dylan Ratcliffe"
